const Discord = require('discord.js');
module.exports = {
	name: 'userinfo',
	description: 'hug someone!',
	aliases: ['ui', 'user-info'],

	execute(message)
	{
		function EmbedCreator() {

			let mentionID = message.mentions.users.first().id;
			let mentionUSERNAME = message.mentions.users.first().username;
			let mentionDISPLAYNAME = message.guild.member(message.mentions.users.first()).displayName
			let mentionDiscriminator = message.mentions.users.first().discriminator;
			let mentionSTATUS = message.mentions.users.first().presence.status;
			
			const newEmbed = new Discord.MessageEmbed() //create embed message
			.setColor('#300075') // color of strip on left
			.setTitle('Information About')
			.setDescription(`${mentionUSERNAME}#${mentionDiscriminator}`)
			.setThumbnail(message.mentions.users.first().avatarURL())
			.addFields(
				{ name: `${mentionUSERNAME} ID:`, value: `${mentionID}`, inline: false },
				{ name: `${mentionUSERNAME} Status:`, value: `${mentionSTATUS}`, inline: false },
				{ name: `${mentionUSERNAME} Displayname:`, value: `${mentionDISPLAYNAME}`, inline: false },
				)
				.setTimestamp()
				.setFooter(`Generated by ${message.author.username}#${message.author.discriminator}`, `${message.author.avatarURL()}`);

				message.channel.send(newEmbed);

		}

		function EmbedCreatorDefault() {

			let authorID = message.author.id
			let authorUSERNAME = message.author.username;
			let authorDISPLAYNAME = message.member.displayName
			let authorDiscriminator = message.author.discriminator;
			let authorSTATUS = message.author.presence.status;
			let authorAVATAR = message.author.avatarURL()
			
			const newEmbed = new Discord.MessageEmbed() //create embed message
			.setColor('#300075') // color of strip on left
			.setTitle('Information About')
			.setDescription(`${authorUSERNAME}#${authorDiscriminator}`)
			.setThumbnail(authorAVATAR)
			.addFields(
				{ name: `${authorUSERNAME} ID:`, value: `${authorID}`, inline: false },
				{ name: `${authorUSERNAME} Status:`, value: `${authorSTATUS}`, inline: false },
				{ name: `${authorUSERNAME} Displayname:`, value: `${authorDISPLAYNAME}`, inline: false },
				)
				.setTimestamp()
				.setFooter(`Generated by default because noone was mentioned!`);

				message.channel.send(newEmbed);
		}

		if (!message.mentions.users.size) {
			EmbedCreatorDefault();
		} else {
			EmbedCreator();

		}
	},
};